
module.exports = [
    {short:"  " , name:"Please select a county"},
    {short:"AC" , name:"Allegany County"},
    {short:"AA" , name:"Anne Arundel County"},
    {short:"BC" , name:"Baltimore County"},
    {short:"BA" , name:"Baltimore City"},
    {short:"CA" , name:"Calvert County"},
    {short:"CL" , name:"Caroline County"},
    {short:"CR" , name:"Carroll County"},
    {short:"CE" , name:"Cecil County"},
    {short:"CH" , name:"Charles County"},
    {short:"DC" , name:"Dorchester County"},
    {short:"FC" , name:"Frederick County"},
    {short:"GC" , name:"Garrett County"},
    {short:"HC" , name:"Harford County"},
    {short:"HO" , name:"Howard County"},
    {short:"KC" , name:"Kent County"},
    {short:"MC" , name:"Montgomery County"},
    {short:"PG" , name:"Prince George's County"},
    {short:"QA" , name:"Queen Anne's County"},
    {short:"SM" , name:"Saint Mary's County"},
    {short:"SC" , name:"Somerset County"},
    {short:"TC" , name:"Talbot County"},
    {short:"WC" , name:"Washington County"},
    {short:"WC" , name:"Wicomico County"},
    {short:"WC" , name:"Worcester County"}
]